project_id = "xqugydhdtlzmtctdbrai"

[functions.send-form-email]
verify_jwt = false

[functions.typeform-webhook]
verify_jwt = false

[functions.resource-waitlist]
verify_jwt = false

[functions.tool-request-notification]
verify_jwt = false
